/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness */
    get: operations["readiness_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Login */
    get: operations["login_auth_login_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Callback */
    get: operations["callback_auth_callback_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Session Info */
    get: operations["session_info_api_session_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Rules */
    get: operations["rules_api_rules_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Workspaces */
    get: operations["workspaces_api_workspaces_get"];
    put?: never;
    /** Setup */
    post: operations["setup_api_workspaces_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Revise Setup */
    put: operations["revise_setup_api_workspaces__wid__setup_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Workspace */
    get: operations["workspace_api_workspaces__wid__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/imports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload */
    post: operations["upload_api_workspaces__wid__imports_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/imports/{bid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Preview */
    get: operations["preview_api_workspaces__wid__imports__bid__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/imports/{bid}/raw": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Raw */
    get: operations["raw_api_workspaces__wid__imports__bid__raw_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activate */
    post: operations["activate_api_workspaces__wid__activate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/draft": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Save */
    post: operations["save_api_workspaces__wid__draft_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/analysis": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Analysis State */
    get: operations["analysis_state_api_workspaces__wid__analysis_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/projections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Projection Upload */
    post: operations["projection_upload_api_workspaces__wid__projections_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/projections/{bid}/review": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Projection Review */
    post: operations["projection_review_api_workspaces__wid__projections__bid__review_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/analysis/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Analysis Activate */
    post: operations["analysis_activate_api_workspaces__wid__analysis_activate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/preferences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preference */
    post: operations["preference_api_workspaces__wid__preferences_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/mappings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mapping */
    post: operations["mapping_api_workspaces__wid__mappings_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/availability": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Availability */
    post: operations["availability_api_workspaces__wid__availability_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/decision-history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Decision History */
    get: operations["decision_history_api_workspaces__wid__decision_history_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/odds": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Odds */
    post: operations["odds_api_workspaces__wid__odds_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/undo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Undo */
    post: operations["undo_api_workspaces__wid__undo_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/entered": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Entered */
    post: operations["entered_api_workspaces__wid__entered_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/entered-dispute": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Entered Dispute */
    post: operations["entered_dispute_api_workspaces__wid__entered_dispute_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/reconcile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reconcile */
    post: operations["reconcile_api_workspaces__wid__reconcile_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/reconcile-preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reconcile Preview */
    post: operations["reconcile_preview_api_workspaces__wid__reconcile_preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/alternatives": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Alternatives */
    post: operations["alternatives_api_workspaces__wid__alternatives_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Complete */
    post: operations["complete_api_workspaces__wid__complete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/completions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Recent Completions */
    get: operations["recent_completions_api_workspaces__wid__completions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/completions/{rid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Completed */
    get: operations["completed_api_workspaces__wid__completions__rid__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workspaces/{wid}/completions/{rid}/apply": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply Completed */
    post: operations["apply_completed_api_workspaces__wid__completions__rid__apply_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Index */
    get: operations["index__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActivateAnalysis */
    ActivateAnalysis: {
      /** Expected Revision */
      expected_revision: number;
      /** Candidate Id */
      candidate_id: string;
    };
    /** Activation */
    Activation: {
      /** Expected Revision */
      expected_revision: number;
      /** Batch Id */
      batch_id: string;
      /** Batch Revision */
      batch_revision: number;
    };
    /** Alternatives */
    Alternatives: {
      /** Expected Revision */
      expected_revision: number;
      /** Include */
      include?: string[];
      /** Exclude */
      exclude?: string[];
    };
    /** ApplyCandidate */
    ApplyCandidate: {
      /** Expected Revision */
      expected_revision: number;
      /**
       * Candidate Index
       * @default 0
       */
      candidate_index: number;
    };
    /** Availability */
    Availability: {
      /** Expected Revision */
      expected_revision: number;
      /** Subject Id */
      subject_id: string;
      /** Game Id */
      game_id: string;
      /**
       * Evidence Type
       * @enum {string}
       */
      evidence_type: "designation" | "participation" | "practice" | "resolution";
      /**
       * Designation
       * @enum {string}
       */
      designation:
        | "Out"
        | "Inactive"
        | "IR"
        | "PUP"
        | "NFI"
        | "Suspended"
        | "Reported absence"
        | "Q"
        | "D"
        | "DTD"
        | "Limited"
        | "Active"
        | "Unknown";
      /** Source */
      source: string;
      /** Source Time */
      source_time?: string | null;
      /** Reason */
      reason: string;
      /** Resolves */
      resolves?: string[];
    };
    /** Body_projection_upload_api_workspaces__wid__projections_post */
    Body_projection_upload_api_workspaces__wid__projections_post: {
      /** Files */
      files: string[];
      /** Positions */
      positions: string;
      /** Declaration */
      declaration: string;
    };
    /** Body_upload_api_workspaces__wid__imports_post */
    Body_upload_api_workspaces__wid__imports_post: {
      /** File */
      file: string;
    };
    /** DisputeInput */
    DisputeInput: {
      /** Expected Revision */
      expected_revision: number;
      /** Reason */
      reason: string;
      /** Reference */
      reference: string;
    };
    /** DraftCommand */
    DraftCommand: {
      /** Expected Revision */
      expected_revision: number;
      /** Operations */
      operations: components["schemas"]["Operation"][];
    };
    /** EnteredInput */
    EnteredInput: {
      /** Expected Revision */
      expected_revision: number;
      /**
       * Draft Id
       * Format: uuid
       */
      draft_id: string;
      /**
       * Attestation
       * @constant
       */
      attestation: "Record as entered in Yahoo";
      /** Reason */
      reason: string;
    };
    /** Expected */
    Expected: {
      /** Expected Revision */
      expected_revision: number;
    };
    /** GameInput */
    GameInput: {
      /** Event Key */
      event_key: string;
      /** Away */
      away: string;
      /** Home */
      home: string;
      /** Kickoff */
      kickoff: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Mapping */
    Mapping: {
      /** Expected Revision */
      expected_revision: number;
      /** Batch Id */
      batch_id: string;
      /** Source Key */
      source_key: string;
      /** Entry Id */
      entry_id: string;
      /** Subject Id */
      subject_id: string;
      /** Reason */
      reason: string;
    };
    /** OddsInput */
    OddsInput: {
      /** Expected Revision */
      expected_revision: number;
      /** Expected Context Revision */
      expected_context_revision: number;
      /**
       * Game Id
       * Format: uuid
       */
      game_id: string;
      /** Source */
      source: string;
      /** Reference */
      reference: string;
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string;
      /** Published At */
      published_at?: string | null;
      /** Total */
      total: string;
      /** Home Spread */
      home_spread: string;
      /**
       * Market
       * @default full-game
       * @constant
       */
      market: "full-game";
      /**
       * Convention
       * @default home-team
       * @constant
       */
      convention: "home-team";
      /** Supersedes */
      supersedes?: string | null;
      /**
       * Reason
       * @default Initial observation
       */
      reason: string;
    };
    /** Operation */
    Operation: {
      /**
       * Op
       * @enum {string}
       */
      op: "add" | "replace" | "remove";
      /** Slot */
      slot: string;
      /** Entry Id */
      entry_id?: string | null;
    };
    /** Preference */
    Preference: {
      /** Expected Revision */
      expected_revision: number;
      /** Entry Id */
      entry_id: string;
      /** Subject Id */
      subject_id: string;
      /**
       * Value
       * @enum {string}
       */
      value: "keep" | "avoid" | "clear";
      /**
       * Remove Selected
       * @default false
       */
      remove_selected: boolean;
    };
    /** ReconcileInput */
    ReconcileInput: {
      /** Expected Revision */
      expected_revision: number;
      /** Preview Hash */
      preview_hash?: string | null;
      /** Draft Id */
      draft_id: string | null;
      /** Entered Id */
      entered_id: string | null;
      /** Assignments */
      assignments: {
        [key: string]: string;
      };
      /** Draft Assignments */
      draft_assignments?: {
        [key: string]: string;
      } | null;
      /**
       * Attestation
       * @constant
       */
      attestation: "Correct historical Yahoo facts; this does not authorize a late selection";
      /** Reason */
      reason: string;
      /** Reference */
      reference: string;
      /** Reported At */
      reported_at?: string | null;
    };
    /** SetupInput */
    SetupInput: {
      /** Name */
      name: string;
      /** Yahoo Id */
      yahoo_id: string;
      /** Season */
      season: string;
      /** Round */
      round: string;
      /**
       * Timezone
       * @default America/Chicago
       */
      timezone: string;
      /** Games */
      games: components["schemas"]["GameInput"][];
      /**
       * Confirmed
       * @constant
       */
      confirmed: true;
      /** Provenance */
      provenance: string;
      /** Expected Revision */
      expected_revision?: number | null;
      /**
       * Membership Change Confirmed
       * @default false
       */
      membership_change_confirmed: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  readiness_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  login_auth_login_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  callback_auth_callback_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  session_info_api_session_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  rules_api_rules_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  workspaces_api_workspaces_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
    };
  };
  setup_api_workspaces_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetupInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revise_setup_api_workspaces__wid__setup_put: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetupInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  workspace_api_workspaces__wid__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_api_workspaces__wid__imports_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_api_workspaces__wid__imports_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  preview_api_workspaces__wid__imports__bid__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wid: string;
        bid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  raw_api_workspaces__wid__imports__bid__raw_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wid: string;
        bid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  activate_api_workspaces__wid__activate_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Activation"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  save_api_workspaces__wid__draft_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DraftCommand"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  analysis_state_api_workspaces__wid__analysis_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  projection_upload_api_workspaces__wid__projections_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_projection_upload_api_workspaces__wid__projections_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  projection_review_api_workspaces__wid__projections__bid__review_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wid: string;
        bid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  analysis_activate_api_workspaces__wid__analysis_activate_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActivateAnalysis"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  preference_api_workspaces__wid__preferences_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Preference"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  mapping_api_workspaces__wid__mappings_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Mapping"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  availability_api_workspaces__wid__availability_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Availability"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  decision_history_api_workspaces__wid__decision_history_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  odds_api_workspaces__wid__odds_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OddsInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  undo_api_workspaces__wid__undo_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Expected"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  entered_api_workspaces__wid__entered_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EnteredInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  entered_dispute_api_workspaces__wid__entered_dispute_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DisputeInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reconcile_api_workspaces__wid__reconcile_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReconcileInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reconcile_preview_api_workspaces__wid__reconcile_preview_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReconcileInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  alternatives_api_workspaces__wid__alternatives_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Alternatives"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  complete_api_workspaces__wid__complete_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Expected"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  recent_completions_api_workspaces__wid__completions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  completed_api_workspaces__wid__completions__rid__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wid: string;
        rid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  apply_completed_api_workspaces__wid__completions__rid__apply_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        wid: string;
        rid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplyCandidate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  index__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
